### ISSUE TITLE
estimate_p6l_relative_pose

### ISSUE THREAD

**Issue by ymx2000** [Fusroda-h/ppl#1] opened 2023-10-24 07:04 UTC
when i running codes in python main.py -d gerrard_hall -e true -r true -t true -i true

it It reported an error and reminded me:
 File "main.py", line 129, in <module>
    main()
  File "main.py", line 97, in main
    inst.estimatePose(query_id)
  File "/remote-home/cs_ai_hch/ymx/PPL/domain/ppl.py", line 117, in estimatePose
    res = poselib.estimate_p6l_relative_pose(self._x1, self._p2, self._x2, cam_p6l, cam_p6l, variable.RANSAC_OPTIONS, variable.BUNDLE_OPTIONS, variable.REFINE_OPTION)
AttributeError: module 'poselib' has no attribute 'estimate_p6l_relative_pose'

but it exists in poselib

**Comment by Fusroda-h** [comment] 2023-10-24 08:56
Please, check if there were any errors when building `poselib`.
It seems like `poselib` library has not been built correctly.

Maybe ur getting this error because of configuration problems.
You can refer to the building method introduced here: https://github.com/PoseLib/PoseLib.

If the problem is not resolved, feel free to leave a question here.

**Comment by ymx2000** [comment] 2023-10-24 11:37
Your PPL project also has the PoseLib folder.

I want to know that I use all the files from the Github project PoseLib in PPL.

Or use the PoseLib in your project and copy the missing ones from Github?

**Comment by ymx2000** [comment] 2023-10-24 11:47
Can you send me a copy of the PoseLib folder in the PPL that can run?

**Comment by ymx2000** [comment] 2023-10-26 01:56
This time I rebuilt the PPL project, where I included PoseLib from Github in your PPL project, and replaced the PoseLib, Pybind, and CMakeLists.txt files in PoseLib with the ones provided in your PPL. But running still prompts for no estimate_ P6l_ Relative_ The pose function.

**Comment by ymx2000** [comment] 2023-10-30 11:52
when i run bash start.sh, it reminds me that does not appear to contain CMakeLists.txt.
which CMakeLists.txt should i select?

**Comment by ymx2000** [comment] 2023-10-30 11:52
CMake Error: The source directory "/remote-home/cs_ai_hch/ymx/PPL_Test/PPL_1/ppl/PoseLib/_build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by Fusroda-h** [comment] 2023-11-01 05:36
I updated the detailed installation method on README.
There was a mismatch with the updated `PoseLib' library and I resolved this issue.

If you have another problem, please leave a comment here.

**Comment by ymx2000** [comment] 2023-11-01 12:50
when i running cmake -S . -B _build/ -DPYTHON_PACKAGE=ON -DCMAKE_INSTALL_PREFIX=_install
it reminds me that "CMake Error: The source directory "/home/jay/PPL_Test/ppl/PoseLib/_build" does not appear to contain CMakeLists.txt." . then i copy CMakeLists.txt from /ppl/PoseLib/CMakeLists.txt  into /ppl/PoseLib/_build/CMakeLists.txt.

this time it reports that 
"CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    /home/jay/PPL_Test/ppl/PoseLib/_build/cmake/SetEnv.cmake


CMake Error at CMakeLists.txt:14 (add_subdirectory):
  add_subdirectory given source "PoseLib" which is not an existing directory.


CMake Error at CMakeLists.txt:25 (add_subdirectory):
  add_subdirectory given source "pybind" which is not an existing directory.


CMake Error at CMakeLists.txt:32 (target_compile_options):
  Cannot specify compile options for target "PoseLib" which is not built by
  this project.


CMake Error at CMakeLists.txt:37 (target_compile_options):
  Cannot specify compile options for target "PoseLib" which is not built by
  this project."
so i copy cmake、PoseLib and pybind from /ppl/PoseLib into /ppl/PoseLib/_build. and this time it reports that "Build files have been written to: /home/jay/PPL_Test/ppl/PoseLib".
i wonder whether this approach is true?

**Comment by ymx2000** [comment] 2023-11-01 13:01
and after that, when I input "cmake --build _build/ --target install" it reports that  "Error: could not load cache".
I meet some problems in trying to run this project. so I sincerely hope you can help me to solve problems and running this project successful.
I was wondering if you could share a configuration video of configuring PPL and running it successfully. Or share a more detailed configuration step? I would be grateful if you could, as it will be more convenient for more researchers.

**Comment by Fusroda-h** [comment] 2023-11-02 01:41
I think the problem you are suffering from occurred in the process of building PoseLib.
Did you succeed in building PoseLib **alone** in your environment following the description from [PoseLib](https://github.com/PoseLib/PoseLib)?
I might help you personally, but I don't think this issue is related to the code.
Leave a message on my [e-mail](jungwhan612@gmail.com).

I think the issue from now on is related to PoseLib, so I am closing this.

**Closed as completed** 2023-11-02 01:41 UTC
